# Generated by Django 5.1.7 on 2025-03-10 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="pizza",
            fields=[
                ("ID", models.IntegerField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=100)),
                ("Size", models.CharField(max_length=6)),
                ("Price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("Description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="order",
            fields=[
                ("ID", models.IntegerField(primary_key=True, serialize=False)),
                ("Order_date", models.DateTimeField(auto_now_add=True)),
                ("Status", models.CharField(max_length=9)),
                ("Total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Forward_order", models.BooleanField(default=False)),
                ("Forward_order_time", models.DateTimeField()),
                (
                    "User_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User_ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="payment",
            fields=[
                ("Transaction_ID", models.IntegerField(auto_created=True)),
                ("ID", models.IntegerField(primary_key=True, serialize=False)),
                ("Payment_method", models.CharField(max_length=12)),
                ("Payment_status", models.CharField(max_length=8)),
                (
                    "Order_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pizza.order",
                        verbose_name="Order_ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="order_item",
            fields=[
                ("ID", models.IntegerField(primary_key=True, serialize=False)),
                ("Quantity", models.IntegerField()),
                (
                    "Order_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pizza.order",
                        verbose_name="Order_ID",
                    ),
                ),
                (
                    "Pizza_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pizza.pizza",
                        verbose_name="Pizza_ID",
                    ),
                ),
            ],
        ),
    ]
