# Generated by Django 5.1.7 on 2025-03-10 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="ID",
            field=models.IntegerField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="order_item",
            name="ID",
            field=models.IntegerField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="order_item",
            name="Pizza_ID",
            field=models.IntegerField(
                verbose_name=models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to="app.model",
                    verbose_name="Pizza_ID",
                )
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="ID",
            field=models.IntegerField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="pizza",
            name="ID",
            field=models.IntegerField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
