# Generated by Django 5.1.7 on 2025-03-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0002_alter_order_id_alter_order_item_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="order_item", new_name="OrderItem",),
        migrations.RenameField(
            model_name="order", old_name="Forward_order", new_name="forward_order",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="Forward_order_time",
            new_name="forward_order_time",
        ),
        migrations.RenameField(model_name="order", old_name="ID", new_name="id",),
        migrations.RenameField(
            model_name="order", old_name="Order_date", new_name="order_date",
        ),
        migrations.RenameField(
            model_name="order", old_name="Status", new_name="status",
        ),
        migrations.RenameField(
            model_name="order", old_name="Total_price", new_name="total_price",
        ),
        migrations.RenameField(
            model_name="order", old_name="User_ID", new_name="user_id",
        ),
        migrations.RenameField(model_name="orderitem", old_name="ID", new_name="id",),
        migrations.RenameField(
            model_name="orderitem", old_name="Order_ID", new_name="order_id",
        ),
        migrations.RenameField(
            model_name="orderitem", old_name="Pizza_ID", new_name="pizza_id",
        ),
        migrations.RenameField(
            model_name="orderitem", old_name="Quantity", new_name="quantity",
        ),
        migrations.RenameField(model_name="payment", old_name="ID", new_name="id",),
        migrations.RenameField(
            model_name="payment", old_name="Order_ID", new_name="order_id",
        ),
        migrations.RenameField(
            model_name="payment", old_name="Payment_method", new_name="payment_method",
        ),
        migrations.RenameField(
            model_name="payment", old_name="Payment_status", new_name="payment_status",
        ),
        migrations.RenameField(
            model_name="payment", old_name="Transaction_ID", new_name="transaction_id",
        ),
        migrations.RenameField(
            model_name="pizza", old_name="Description", new_name="description",
        ),
        migrations.RenameField(model_name="pizza", old_name="ID", new_name="id",),
        migrations.RenameField(model_name="pizza", old_name="Name", new_name="name",),
        migrations.RenameField(model_name="pizza", old_name="Price", new_name="price",),
        migrations.RenameField(model_name="pizza", old_name="Size", new_name="size",),
    ]
