# Generated by Django 5.1.7 on 2025-03-11 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0003_rename_order_item_orderitem_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="payment", name="transaction_id",),
        migrations.AlterField(
            model_name="order",
            name="forward_order",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], default=False
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Prepared", "Prepared"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="pizza_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pizza.pizza",
                verbose_name="Pizza_ID",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Credit Card", "Credit Card"),
                    ("PayPal", "PayPal"),
                    ("Cash", "Cash"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Paid", "Paid"),
                    ("Pending", "Pending"),
                    ("Failed", "Failed"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="pizza",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="pizza",
            name="size",
            field=models.CharField(
                choices=[("Small", "Small"), ("Medium", "Medium"), ("Large", "Large")],
                max_length=6,
            ),
        ),
    ]
