# Generated by Django 5.1.7 on 2025-03-12 10:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0004_remove_payment_transaction_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pizza",
            name="featured_image",
            field=cloudinary.models.CloudinaryField(
                default="placeholder", max_length=255, verbose_name="image"
            ),
        ),
    ]
