# Generated by Django 5.1.7 on 2025-03-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0005_pizza_featured_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="pizza",
            name="enabled",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], default=True
            ),
        ),
    ]
