# Generated by Django 5.1.7 on 2025-03-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0007_alter_pizza_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("read", models.BooleanField(default=False)),
            ],
        ),
    ]
