# Generated by Django 5.1.7 on 2025-03-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0008_contactus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Cart", "Cart"),
                    ("Pending", "Pending"),
                    ("Prepared", "Prepared"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                max_length=9,
            ),
        ),
    ]
