# Generated by Django 5.1.7 on 2025-03-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0009_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
